package views;

import popUp.Nilai;
import java.sql.*;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import config.Koneksi;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Rizki Maulana
 */
public class Bobot extends javax.swing.JInternalFrame {
    private Connection conn = new Koneksi().getKoneksi();
    private DefaultTableModel tabmode;

    /**
     * Creates new form BarangMasuk
     */
    public Bobot() {
        initComponents();
        dataTable();
        kdBob();
        penMax();
        attMax();
        komMax();
        pengMax();
        karMax();
        hiding();
        weight();
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengeluaranPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tabelPengeluaran = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        hapusPenjualan1 = new javax.swing.JButton();
        tambahPenjualan1 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        pilihKandidat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        w1 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        pe1 = new javax.swing.JTextField();
        ptot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pe2 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        w2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        m3 = new javax.swing.JTextField();
        pe3 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        w3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        w4 = new javax.swing.JTextField();
        pe4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        w5 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        pe5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        Cetak1 = new javax.swing.JButton();

        pengeluaranPanel.setBackground(new java.awt.Color(102, 153, 255));
        pengeluaranPanel.setPreferredSize(new java.awt.Dimension(1124, 736));

        tabelPengeluaran.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabelPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pengeluaran", "Tanggal Pengeluaran", "Kode Produk", "Barang Dibeli", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tabelPengeluaran);

        jLabel43.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(232, 238, 204));
        jLabel43.setText("Bobot Nilai");

        hapusPenjualan1.setText("Hapus");
        hapusPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPenjualan1ActionPerformed(evt);
            }
        });

        tambahPenjualan1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tambahPenjualan1.setText("Tambah");
        tambahPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenjualan1ActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(232, 238, 204));
        jLabel44.setText("Bobot");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 238, 204));
        jLabel6.setText("Kode Kandidat");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(232, 238, 204));
        jLabel13.setText("Kode Botot");

        kdKandidat.setEditable(false);
        kdKandidat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kdKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdKandidatActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        kdBobot.setEditable(false);
        kdBobot.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kdBobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdBobotActionPerformed(evt);
            }
        });

        pilihKandidat.setText("Pilih Kandidat");
        pilihKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKandidatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 238, 204));
        jLabel7.setText("Penampilan");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 238, 204));
        jLabel12.setText("Weight");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 238, 204));
        jLabel14.setText("Score");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 238, 204));
        jLabel15.setText("Pembagi(max)");

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(232, 238, 204));
        jLabel16.setText("Matriks");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(232, 238, 204));
        jLabel17.setText("Penilaian");

        w1.setEditable(false);

        s1.setEditable(false);

        p1.setEditable(false);

        m1.setEditable(false);

        pe1.setEditable(false);

        ptot.setEditable(false);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(232, 238, 204));
        jLabel18.setText("Total");

        pe2.setEditable(false);

        m2.setEditable(false);

        p2.setEditable(false);

        s2.setEditable(false);

        w2.setEditable(false);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 238, 204));
        jLabel8.setText("Attitude");

        m3.setEditable(false);

        pe3.setEditable(false);

        p3.setEditable(false);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 238, 204));
        jLabel9.setText("Komunikasi");

        w3.setEditable(false);

        s3.setEditable(false);

        s4.setEditable(false);

        p4.setEditable(false);

        m4.setEditable(false);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 238, 204));
        jLabel10.setText("Pengalaman");

        w4.setEditable(false);

        pe4.setEditable(false);

        s5.setEditable(false);

        p5.setEditable(false);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 238, 204));
        jLabel11.setText("Karakter");

        w5.setEditable(false);

        m5.setEditable(false);

        pe5.setEditable(false);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cetak.setText("Laporan Nilai");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        Cetak1.setText("Laporan Nilai Teratas");
        Cetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cetak1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pengeluaranPanelLayout = new javax.swing.GroupLayout(pengeluaranPanel);
        pengeluaranPanel.setLayout(pengeluaranPanelLayout);
        pengeluaranPanelLayout.setHorizontalGroup(
            pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel44))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(kdBobot, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(kdKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(pilihKandidat))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel15)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(w1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(pe1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(w2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(pe2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(w3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(pe3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(w4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(pe4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(w5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(pe5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel43))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tambahPenjualan1)
                        .addGap(207, 207, 207)
                        .addComponent(reset)
                        .addGap(14, 14, 14)
                        .addComponent(hapusPenjualan1))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(ptot, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1))
                            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cetak)
                                    .addComponent(Cetak1))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        pengeluaranPanelLayout.setVerticalGroup(
            pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(kdBobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(kdKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pilihKandidat)))
                .addGap(6, 6, 6)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ptot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(5, 5, 5)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                        .addComponent(Cetak)
                        .addGap(18, 18, 18)
                        .addComponent(Cetak1)))
                .addGap(6, 6, 6)
                .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahPenjualan1)
                    .addGroup(pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hapusPenjualan1)
                        .addComponent(reset)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pengeluaranPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         protected void aktif() {
        kdBobot.setEnabled(true);
        kdKandidat.setEnabled(true);
    }
    
    protected void kosong () {
        kdBobot.setText("");
        kdKandidat.setText("");
        s1.setText("");
        s2.setText("");
        s3.setText("");
        s4.setText("");
        s5.setText("");
        m1.setText("");
        m2.setText("");
        m3.setText("");
        m4.setText("");
        m5.setText("");
        pe1.setText("");
        pe2.setText("");
        pe3.setText("");
        pe4.setText("");
        pe5.setText("");
        ptot.setText("");
    }
    
    //hide 
    private void hiding() {
        jLabel17.setVisible(false);
        pe1.setVisible(false);
        pe2.setVisible(false);
        pe3.setVisible(false);
        pe4.setVisible(false);
        pe5.setVisible(false);
        jLabel15.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }
    
    public void kdBob() {
        try{
            String sql = "SELECT MAX(right(kd_bob, 2)) AS kode_masuk FROM bobot";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                if(rs.first()==false) {
                    kdBobot.setText("Bob-001");
                } else {
                    rs.last();
                    int kd_masuk = rs.getInt(1) + 1;
                    String nomor = String.valueOf(kd_masuk);
                    int kdMasuk = nomor.length();
                    
                    for (int i = 0; i<3-kdMasuk; i++) {
                        nomor = "0" + nomor;
                    }
                    kdBobot.setText("Bob-" + nomor);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal " +e.getMessage());
        }
    }
    
    
    //find max
    private void penMax() {
        try {
        String sql = "SELECT MAX(penampilan) as maxpen from nilai";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        
        if (rs.next()) {
            String maxpen = rs.getString("maxpen");
            p1.setText(maxpen);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }
    private void attMax() {
        try {
        String sql = "SELECT MAX(attitude) as maxatt from nilai";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        
        if (rs.next()) {
            String maxatt = rs.getString("maxatt");
            p2.setText(maxatt);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }
    private void komMax() {
        try {
        String sql = "SELECT MAX(komunikasi) as maxkom from nilai";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        
        if (rs.next()) {
            String maxkom = rs.getString("maxkom");
            p3.setText(maxkom);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }
    private void pengMax() {
        try {
        String sql = "SELECT MAX(pengalaman) as maxpeng from nilai";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        
        if (rs.next()) {
            String maxpeng = rs.getString("maxpeng");
            p4.setText(maxpeng);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }
    private void karMax() {
        try {
        String sql = "SELECT MAX(karakter) as maxkar from nilai";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        
        if (rs.next()) {
            String maxkar = rs.getString("maxkar");
            p5.setText(maxkar);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }
    //end of cari max
    
    //hitung matriks
    private void hitungpen() {
        Double penmax = Double.parseDouble(p1.getText());
        Double spen = Double.parseDouble(s1.getText());
        Double matpen = spen/penmax;
        m1.setText(String.valueOf(matpen));
    }
    
    private void hitungatt() {
        Double attmax = Double.parseDouble(p2.getText());
        Double satt = Double.parseDouble(s2.getText());
        Double matatt = satt/attmax;
        m2.setText(String.valueOf(matatt));
    }
    
    private void hitungkom() {
        Double kommax = Double.parseDouble(p3.getText());
        Double skom = Double.parseDouble(s3.getText());
        Double matkom = skom/kommax;
        m3.setText(String.valueOf(matkom));
    }
    
    private void hitungpeng() {
        Double pengmax = Double.parseDouble(p4.getText());
        Double speng = Double.parseDouble(s4.getText());
        Double matpeng = speng/pengmax;
        m4.setText(String.valueOf(matpeng));
    }
    
    private void hitungkar() {
        Double karmax = Double.parseDouble(p5.getText());
        Double skar = Double.parseDouble(s5.getText());
        Double matkar = skar/karmax;
        m5.setText(String.valueOf(matkar));
    }
    //end of matriks
    
    //hitung penilaian
        private void penpen() {
        Double mpen = Double.parseDouble(m1.getText());
        Double wpen = Double.parseDouble(w1.getText());
        Double vpen = mpen*wpen;
        pe1.setText(String.valueOf(vpen));
    }
    
    private void penatt() {
        Double matt = Double.parseDouble(m2.getText());
        Double watt = Double.parseDouble(w2.getText());
        Double vatt = matt*watt;
        pe2.setText(String.valueOf(vatt));
    }
    
    private void penkom() {
        Double mkom = Double.parseDouble(m3.getText());
        Double wkom = Double.parseDouble(w3.getText());
        Double vkom = mkom*wkom;
        pe3.setText(String.valueOf(vkom));
    }
    
    private void penpeng() {
        Double mpeng = Double.parseDouble(m4.getText());
        Double wpeng = Double.parseDouble(w4.getText());
        Double vpeng = mpeng*wpeng;
        pe4.setText(String.valueOf(vpeng));
    }
    
    private void penkar() {
        Double mkar = Double.parseDouble(m5.getText());
        Double wkar = Double.parseDouble(w5.getText());
        Double vkar = mkar*wkar;
        pe5.setText(String.valueOf(vkar));
    }
    
    private void pentot() {
        double vpen = Double.parseDouble(pe1.getText());
        double vatt = Double.parseDouble(pe2.getText());
        double vkom = Double.parseDouble(pe3.getText());
        double vpeng = Double.parseDouble(pe4.getText());
        double vkar = Double.parseDouble(pe5.getText());
        double vtotal = vpen+vatt+vkom+vpeng+vkar;
        ptot.setText(String.valueOf(vtotal));
        
    }
    //end of penilaian
    
    protected void dataTable() {
        DefaultTableModel tabelDataPengeluaran = new DefaultTableModel();
        tabelDataPengeluaran.addColumn("No");
        tabelDataPengeluaran.addColumn("Kode Bobot");
        tabelDataPengeluaran.addColumn("Nama Kandidat");
        tabelDataPengeluaran.addColumn("Nilai");
        
        try {
            int no = 1;
            String sql = "SELECT bobot.kd_bob, recruitment.nama_kandidat, bobot.vtotal "
                       + "FROM `bobot` "
                       + "INNER JOIN recruitment ON recruitment.kd_kan = bobot.kd_kan "
                       + "ORDER BY `bobot`.`vtotal` DESC ";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                tabelDataPengeluaran.addRow(new Object[]{
                   no++,
                   rs.getString(1),
                   rs.getString(2),
                   rs.getString(3),
                });
            }
            tabelPengeluaran.setModel(tabelDataPengeluaran);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal a "+e.getMessage());
        }
    }
    
    //isi weight
    public void weight() {    
    String sqlPen = "SELECT penampilan, attitude, komunikasi, pengalaman, karakter FROM `kriteria`";
    try {
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sqlPen);
        
        if(rs.next()){
            w1.setText(rs.getString(1));
            w2.setText(rs.getString(2));
            w3.setText(rs.getString(3));
            w4.setText(rs.getString(4));
            w5.setText(rs.getString(5));
        } 
    } catch(SQLException e) {
        JOptionPane.showMessageDialog(null,"Koneksi Gagal " + e.getMessage());
    }
    
    }
    private void pilihKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKandidatActionPerformed
        // TODO add your handling code here:
        new Nilai().setVisible(true);
    }//GEN-LAST:event_pilihKandidatActionPerformed

    private void kdBobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdBobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdBobotActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
        kdBob();
    }//GEN-LAST:event_resetActionPerformed

    private void kdKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdKandidatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdKandidatActionPerformed

    private void tambahPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenjualan1ActionPerformed
        // TODO add your handling code here:
         String sql = "INSERT INTO `bobot` (`kd_bob`, `kd_kan`, `vpenampilan`, `vattitude`, `vkomunikasi`, `vpengalaman`, `vkarakter`, `vtotal`) VALUES (?,?,?,?,?,?,?,?)";
         
         try {
             PreparedStatement stat = conn.prepareStatement(sql);
             stat.setString(1, kdBobot.getText());
             stat.setString(2, kdKandidat.getText());
             stat.setString(3, m1.getText());
             stat.setString(4, m2.getText());
             stat.setString(5, m3.getText());
             stat.setString(6, m4.getText());
             stat.setString(7, m5.getText());
             stat.setString(8, ptot.getText());
             
             stat.executeUpdate();
             JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
             kosong();
             dataTable();
             kdBob();
         } 
         
         catch(SQLException e) {
             JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
         }
    }//GEN-LAST:event_tambahPenjualan1ActionPerformed

    private void hapusPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPenjualan1ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0) {
            String sql = "DELETE FROM bobot WHERE `bobot`.`kd_bob` = '" + kdBobot.getText()+ "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                kdBobot.requestFocus();
                dataTable();
                kdBob();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }
    }//GEN-LAST:event_hapusPenjualan1ActionPerformed

    private void tabelPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengeluaranMouseClicked
        // TODO add your handling code here:
        int bar = tabelPengeluaran.getSelectedRow();
        String a = tabelPengeluaran.getValueAt(bar, 0).toString();
        String b = tabelPengeluaran.getValueAt(bar, 1).toString();
        String c = tabelPengeluaran.getValueAt(bar, 2).toString();
        String d = tabelPengeluaran.getValueAt(bar, 3).toString();

        kdBobot.setText(b);
        kdKandidat.setText(c);
    }//GEN-LAST:event_tabelPengeluaranMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hitungpen();
        hitungatt();
        hitungkom();
        hitungpeng();
        hitungkar();
        penpen();
        penatt();
        penkom();
        penpeng();
        penkar();
        pentot();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Koneksi.getKoneksi();
            String report ="/report/report4.jasper";
            InputStream path = getClass().getResourceAsStream(report);
            HashMap hash = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(path, hash, conn);
            JasperViewer.viewReport(JPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }//GEN-LAST:event_CetakActionPerformed

    private void Cetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cetak1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Koneksi.getKoneksi();
            String report ="/report/report3.jasper";
            InputStream path = getClass().getResourceAsStream(report);
            HashMap hash = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(path, hash, conn);
            JasperViewer.viewReport(JPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }//GEN-LAST:event_Cetak1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Cetak1;
    private javax.swing.JButton hapusPenjualan1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    public static final javax.swing.JTextField kdBobot = new javax.swing.JTextField();
    public static final javax.swing.JTextField kdKandidat = new javax.swing.JTextField();
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField pe1;
    private javax.swing.JTextField pe2;
    private javax.swing.JTextField pe3;
    private javax.swing.JTextField pe4;
    private javax.swing.JTextField pe5;
    private javax.swing.JPanel pengeluaranPanel;
    private javax.swing.JButton pilihKandidat;
    private javax.swing.JTextField ptot;
    private javax.swing.JButton reset;
    public static final javax.swing.JTextField s1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField s2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField s3 = new javax.swing.JTextField();
    public static final javax.swing.JTextField s4 = new javax.swing.JTextField();
    public static final javax.swing.JTextField s5 = new javax.swing.JTextField();
    private javax.swing.JTable tabelPengeluaran;
    private javax.swing.JButton tambahPenjualan1;
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    private javax.swing.JTextField w4;
    private javax.swing.JTextField w5;
    // End of variables declaration//GEN-END:variables
}
