package views;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import config.Koneksi;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import popUp.Jabatan;
import popUp.Recruiter;
import popUp.RecruitmentTerpilih;

/**
 *
 * @author Rizki Maulana
 */
public class Karyawan extends javax.swing.JInternalFrame {
    private Connection conn = new Koneksi().getKoneksi();
//    private DefaultTableModel tabmode;

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        dataTable();
        KdKaryawan();
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        karyawanPanel = new javax.swing.JPanel();
        tambahKaryawan = new javax.swing.JButton();
        hapusKaryawan = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        cariKaryawan = new javax.swing.JTextField();
        ubahKaryawan = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        kodeKaryawan = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        cetak = new javax.swing.JButton();
        calonKaryawan = new javax.swing.JButton();
        pilihJabatan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        getContentPane().setLayout(new java.awt.CardLayout());

        karyawanPanel.setBackground(new java.awt.Color(102, 153, 255));
        karyawanPanel.setPreferredSize(new java.awt.Dimension(1124, 736));
        karyawanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambahKaryawan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tambahKaryawan.setText("Tambah");
        tambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKaryawanActionPerformed(evt);
            }
        });
        karyawanPanel.add(tambahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 629, -1, -1));

        hapusKaryawan.setText("Hapus");
        hapusKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKaryawanActionPerformed(evt);
            }
        });
        karyawanPanel.add(hapusKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 631, -1, -1));

        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(232, 238, 204));
        jLabel47.setText("Data Karyawan");
        karyawanPanel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 320, -1, 33));

        cariKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKaryawanActionPerformed(evt);
            }
        });
        cariKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKaryawanKeyReleased(evt);
            }
        });
        karyawanPanel.add(cariKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 203, -1));

        ubahKaryawan.setText("Update");
        ubahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahKaryawanActionPerformed(evt);
            }
        });
        karyawanPanel.add(ubahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 631, -1, -1));

        jLabel45.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(232, 238, 204));
        jLabel45.setText("Cari");
        karyawanPanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 323, 30, -1));

        tabelKaryawan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Karyawan", "Nama Karyawan", "Kontak", "Kode Jabatan", "Alamat"
            }
        ));
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tabelKaryawan);

        karyawanPanel.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 359, 1004, 256));

        jLabel48.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(232, 238, 204));
        jLabel48.setText("Panel Karyawan");
        karyawanPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, 33));

        jLabel59.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(232, 238, 204));
        jLabel59.setText("Kode Karyawan");
        karyawanPanel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, 33));

        jLabel60.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(232, 238, 204));
        jLabel60.setText("Nama Karyawan");
        karyawanPanel.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 134, -1, 33));

        jLabel61.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(232, 238, 204));
        jLabel61.setText("Kontak");
        karyawanPanel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 153, 96, 33));

        jLabel62.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(232, 238, 204));
        jLabel62.setText("Jabatan");
        karyawanPanel.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 185, 109, 33));

        jLabel63.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(232, 238, 204));
        jLabel63.setText("Alamat");
        karyawanPanel.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 83, 96, 33));

        kodeKaryawan.setEditable(false);
        kodeKaryawan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kodeKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        karyawanPanel.add(kodeKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 87, 220, -1));

        namaKaryawan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        karyawanPanel.add(namaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 140, 220, -1));

        kontakKaryawan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        karyawanPanel.add(kontakKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 157, 228, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        karyawanPanel.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 631, -1, -1));

        gaji.setEditable(false);
        gaji.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        karyawanPanel.add(gaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 205, 228, -1));

        jLabel64.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(232, 238, 204));
        jLabel64.setText("Gaji");
        karyawanPanel.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 199, 96, 33));

        cetak.setText("Cetak Laporan");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        karyawanPanel.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 631, -1, -1));

        calonKaryawan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        calonKaryawan.setText("Pilih Calon Karyawan");
        calonKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calonKaryawanActionPerformed(evt);
            }
        });
        karyawanPanel.add(calonKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 141, -1, -1));

        pilihJabatan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pilihJabatan.setText("Pilih Jabatan");
        pilihJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihJabatanActionPerformed(evt);
            }
        });
        karyawanPanel.add(pilihJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 186, -1, -1));

        jabatan.setEditable(false);
        jabatan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        karyawanPanel.add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 185, 220, -1));

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        karyawanPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 43, 228, -1));

        getContentPane().add(karyawanPanel, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //isi otomatis Kd_karyawan
    public void KdKaryawan() {
        try{
            String sql = "SELECT MAX(right(kd_kar, 2)) AS kode_karyawan FROM karyawan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                if(rs.first()==false){
                    kodeKaryawan.setText("Kar-001");
                } else {
                    rs.last();
                    int id_karyawan = rs.getInt(1) + 1;
                    String nomor = String.valueOf(id_karyawan);
                    int idKaryawan = nomor.length();
                    
                    for (int i=0; i<3-idKaryawan; i++){
                        
                        nomor = "0" + nomor;
                    }
                    kodeKaryawan.setText("Kar-" + nomor);
                 }
            }             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal "+ e.getMessage());
        }
    }
    
    protected void aktif() {
        kodeKaryawan.setEnabled(true);
        namaKaryawan.setEnabled(true);
        kontakKaryawan.setEnabled(true);
        alamat.setEnabled(true);
        kodeKaryawan.requestFocus();
    }
    
    
    protected void kosong() {
        kodeKaryawan.setText("");
        namaKaryawan.setText("");
        kontakKaryawan.setText("");
        alamat.setText("");
        jabatan.setText("");
        gaji.setText("");
    }
    
    //show table
    public void dataTable(){
        DefaultTableModel tableDataKaryawan = new DefaultTableModel();
        tableDataKaryawan.addColumn("No");
        tableDataKaryawan.addColumn("Kode Karyawan");
        tableDataKaryawan.addColumn("Nama Karyawan");
        tableDataKaryawan.addColumn("Jabatan");
        tableDataKaryawan.addColumn("Alamat");
        tableDataKaryawan.addColumn("Kontak");
        tableDataKaryawan.addColumn("Gaji");
        
        String cari = cariKaryawan.getText();
        try {
            int no = 1;
            String sql = "SELECT * FROM `karyawan`";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                tableDataKaryawan.addRow(new Object[]{
                  no++,
                  rs.getString(1),
                  rs.getString(2),
                  rs.getString(3),
                  rs.getString(4),
                  rs.getString(5),
                  rs.getString(6),
                });
            }
            tabelKaryawan.setModel(tableDataKaryawan);
        } catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "Koneksi Gagal "+ e.getMessage());
        }
    }
    
    private void tambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKaryawanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO `karyawan` (`kd_kar`, `nama`, `jabatan`, `alamat`, `hp`, `gaji`) VALUES (?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, kodeKaryawan.getText());
            stat.setString(2, namaKaryawan.getText());
            stat.setString(3, jabatan.getText());
            stat.setString(4, alamat.getText());
            stat.setString(5, kontakKaryawan.getText());
            stat.setString(6, gaji.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Simpan");
            kosong(); 
            namaKaryawan.requestFocus();
            dataTable();
            KdKaryawan();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_tambahKaryawanActionPerformed

    private void hapusKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKaryawanActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            String sql = "DELETE FROM karyawan WHERE `karyawan`.`kd_kar` = '" +kodeKaryawan.getText()+ "'";
            
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                kodeKaryawan.requestFocus();
                dataTable();
                KdKaryawan();
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }
        
    }//GEN-LAST:event_hapusKaryawanActionPerformed

    private void cariKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariKaryawanActionPerformed

    private void ubahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahKaryawanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE `karyawan` SET `nama` = ?, `jabatan` = ?, `alamat` = ?, `hp` = ?, `gaji` = ? WHERE `karyawan`.`kd_kar` = ?;";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, namaKaryawan.getText());
            stat.setString(2, jabatan.getText());
            stat.setString(3, alamat.getText());
            stat.setString(4, kontakKaryawan.getText());
            stat.setString(5, gaji.getText());
            stat.setString(6, kodeKaryawan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            kodeKaryawan.requestFocus();
            dataTable();
            KdKaryawan();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_ubahKaryawanActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int  bar = tabelKaryawan.getSelectedRow();
        String a = tabelKaryawan.getValueAt(bar, 0).toString();
        String b = tabelKaryawan.getValueAt(bar, 1).toString();
        String c = tabelKaryawan.getValueAt(bar, 2).toString();
        String d = tabelKaryawan.getValueAt(bar, 3).toString();
        String e = tabelKaryawan.getValueAt(bar, 4).toString();
        String f = tabelKaryawan.getValueAt(bar, 5).toString();
        String g = tabelKaryawan.getValueAt(bar, 6).toString();
        
        kodeKaryawan.setText(b);
        namaKaryawan.setText(c);
        jabatan.setText(d);
        kontakKaryawan.setText(f);
        alamat.setText(e);
        gaji.setText(g);
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
        KdKaryawan();
    }//GEN-LAST:event_resetActionPerformed

    private void cariKaryawanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKaryawanKeyReleased
        // TODO add your handling code here:
        dataTable();
    }//GEN-LAST:event_cariKaryawanKeyReleased

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Koneksi.getKoneksi();
            String report ="/report/report2.jasper";
            InputStream path = getClass().getResourceAsStream(report);
            HashMap hash = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(path, hash, conn);
            JasperViewer.viewReport(JPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void calonKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calonKaryawanActionPerformed
        // TODO add your handling code here:
        new RecruitmentTerpilih().setVisible(true);
    }//GEN-LAST:event_calonKaryawanActionPerformed

    private void pilihJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihJabatanActionPerformed
        // TODO add your handling code here:
        new Jabatan().setVisible(true);
    }//GEN-LAST:event_pilihJabatanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextArea alamat = new javax.swing.JTextArea();
    private javax.swing.JButton calonKaryawan;
    private javax.swing.JTextField cariKaryawan;
    private javax.swing.JButton cetak;
    public static final javax.swing.JTextField gaji = new javax.swing.JTextField();
    private javax.swing.JButton hapusKaryawan;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    public static final javax.swing.JTextField jabatan = new javax.swing.JTextField();
    private javax.swing.JPanel karyawanPanel;
    private javax.swing.JTextField kodeKaryawan;
    public static final javax.swing.JTextField kontakKaryawan = new javax.swing.JTextField();
    public static final javax.swing.JTextField namaKaryawan = new javax.swing.JTextField();
    private javax.swing.JButton pilihJabatan;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JButton tambahKaryawan;
    private javax.swing.JButton ubahKaryawan;
    // End of variables declaration//GEN-END:variables
}
