package views;

import popUp.Recruiter;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import config.Koneksi;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Rizki Maulana
 */
public class Nilai extends javax.swing.JInternalFrame {
    private Connection conn = new Koneksi().getKoneksi();
    private DefaultTableModel tabmode;

    /**
     * Creates new form BarangKeluar
     */
    public Nilai() {
        initComponents();
        dataTable();
        kdBarangKeluar();
        bobotTable();
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        pengeluaranPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tabelRecruiter = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        cariRecruiter = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        hapusPenjualan1 = new javax.swing.JButton();
        tambahPenjualan1 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        pilihBarang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pen1 = new javax.swing.JRadioButton();
        pen2 = new javax.swing.JRadioButton();
        pen3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        k1 = new javax.swing.JRadioButton();
        k2 = new javax.swing.JRadioButton();
        k3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        peng1 = new javax.swing.JRadioButton();
        peng2 = new javax.swing.JRadioButton();
        peng3 = new javax.swing.JRadioButton();
        ka3 = new javax.swing.JRadioButton();
        ka2 = new javax.swing.JRadioButton();
        ka1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        tabelBobot = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Update1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        pengeluaranPanel.setBackground(new java.awt.Color(102, 153, 255));
        pengeluaranPanel.setPreferredSize(new java.awt.Dimension(1124, 736));
        pengeluaranPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelRecruiter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabelRecruiter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pengeluaran", "Tanggal Pengeluaran", "Kode Produk", "Barang Dibeli", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelRecruiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRecruiterMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tabelRecruiter);

        pengeluaranPanel.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 433, 514, 191));

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(232, 238, 204));
        jLabel42.setText("Cari");
        pengeluaranPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 399, 30, 22));

        cariRecruiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariRecruiterActionPerformed(evt);
            }
        });
        cariRecruiter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariRecruiterKeyReleased(evt);
            }
        });
        pengeluaranPanel.add(cariRecruiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 402, 210, -1));

        jLabel43.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(232, 238, 204));
        jLabel43.setText("Data Recruiter");
        pengeluaranPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 389, -1, 33));

        hapusPenjualan1.setText("Hapus");
        hapusPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPenjualan1ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(hapusPenjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 639, -1, -1));

        tambahPenjualan1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tambahPenjualan1.setText("Tambah");
        tambahPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenjualan1ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(tambahPenjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 640, -1, -1));

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(232, 238, 204));
        jLabel44.setText("Nilai");
        pengeluaranPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, -1, 33));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 238, 204));
        jLabel6.setText("Kode Recruiter");
        pengeluaranPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 118, 148, 39));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(232, 238, 204));
        jLabel13.setText("Kode Nilai");
        pengeluaranPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 61, -1, 39));

        kdRecruiter.setEditable(false);
        kdRecruiter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kdRecruiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdRecruiterActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(kdRecruiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 125, 222, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 640, -1, -1));

        kdKriteria.setEditable(false);
        kdKriteria.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kdKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdKriteriaActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(kdKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 68, 222, -1));

        pilihBarang.setText("Pilih Kandidat");
        pilihBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBarangActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(pilihBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 128, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 238, 204));
        jLabel8.setText("Penampilan");
        pengeluaranPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, 87, 39));

        buttonGroup1.add(pen1);
        pen1.setText("Tidak");
        pengeluaranPanel.add(pen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 171, -1, -1));

        buttonGroup1.add(pen2);
        pen2.setText("Biasa");
        pengeluaranPanel.add(pen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 171, 70, -1));

        buttonGroup1.add(pen3);
        pen3.setText("Rapi");
        pengeluaranPanel.add(pen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 171, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 238, 204));
        jLabel9.setText("Attitude");
        pengeluaranPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 209, 87, 39));

        buttonGroup2.add(a1);
        a1.setText("Tidak Bagus");
        pengeluaranPanel.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 219, -1, -1));

        buttonGroup2.add(a2);
        a2.setText("Normal");
        pengeluaranPanel.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 219, -1, -1));

        buttonGroup2.add(a3);
        a3.setText("Bagus");
        pengeluaranPanel.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 219, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 238, 204));
        jLabel10.setText("Komunikasi");
        pengeluaranPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 254, -1, 39));

        buttonGroup3.add(k1);
        k1.setText("  Tidak Bagus");
        k1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k1ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 264, -1, -1));

        buttonGroup3.add(k2);
        k2.setText("Biasa");
        k2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k2ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 264, -1, -1));

        buttonGroup3.add(k3);
        k3.setText("Bagus");
        pengeluaranPanel.add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 264, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 238, 204));
        jLabel11.setText("Pengalaman");
        pengeluaranPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 299, -1, 39));

        buttonGroup4.add(peng1);
        peng1.setText("1 Tahun");
        pengeluaranPanel.add(peng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 309, -1, -1));

        buttonGroup4.add(peng2);
        peng2.setText("2 Tahun");
        peng2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peng2ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(peng2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 309, -1, -1));

        buttonGroup4.add(peng3);
        peng3.setText(">2 Tahun");
        pengeluaranPanel.add(peng3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 309, -1, -1));

        buttonGroup5.add(ka3);
        ka3.setText("Baik");
        pengeluaranPanel.add(ka3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 354, -1, -1));

        buttonGroup5.add(ka2);
        ka2.setText("Normal");
        ka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ka2ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(ka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 354, -1, -1));

        buttonGroup5.add(ka1);
        ka1.setText("Buruk");
        pengeluaranPanel.add(ka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 354, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 238, 204));
        jLabel12.setText("Karakter");
        pengeluaranPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 344, 85, 39));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 642, -1, -1));

        cetak.setText("Cetak Laporan");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 639, -1, -1));

        tabelBobot.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabelBobot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pengeluaran", "Tanggal Pengeluaran", "Kode Produk", "Barang Dibeli", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBobot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBobotMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tabelBobot);

        pengeluaranPanel.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 433, 506, 191));

        jLabel45.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(232, 238, 204));
        jLabel45.setText("Kriteria");
        pengeluaranPanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 22, -1, 33));

        penampilan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        penampilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penampilanActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(penampilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 130, 140, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 238, 204));
        jLabel14.setText("Kode Kriteria");
        pengeluaranPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 73, -1, 39));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 238, 204));
        jLabel7.setText("Attitude");
        pengeluaranPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 173, 148, 39));

        attitude.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        attitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attitudeActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(attitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 180, 140, -1));

        komunikasi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        komunikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komunikasiActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(komunikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 230, 140, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 238, 204));
        jLabel15.setText("Komunikasi");
        pengeluaranPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 223, 148, 39));

        pengalaman.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pengalaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengalamanActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(pengalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 280, 140, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(232, 238, 204));
        jLabel16.setText("Pengalaman");
        pengeluaranPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 273, 148, 39));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(232, 238, 204));
        jLabel17.setText("Karakter");
        pengeluaranPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 323, 148, 39));

        karakter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        karakter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karakterActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(karakter, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 330, 140, -1));

        Update1.setText("Update Bobot");
        Update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update1ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(Update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 639, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(232, 238, 204));
        jLabel18.setText("Penampilan");
        pengeluaranPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 123, -1, 39));

        kode.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 80, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pengeluaranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void aktif() {
        kdKriteria.setEnabled(true);
        kdRecruiter.setEnabled(true);
//        jumlahMasuk.setEnabled(true);
    }
    
    protected void kosong () {
        kdRecruiter.setText("");
        kode.setText("");
        penampilan.setText("");
        attitude.setText("");
        komunikasi.setText("");
        pengalaman.setText("");
        karakter.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
    }
    
    public void kdBarangKeluar() {
        try{
            String sql = "SELECT MAX(right(kd_nil, 2)) AS kode_keluar FROM nilai";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                if(rs.first()==false) {
                    kdKriteria.setText("Nil-001");
                } else {
                    rs.last();
                    int kd_masuk = rs.getInt(1) + 1;
                    String nomor = String.valueOf(kd_masuk);
                    int kdMasuk = nomor.length();
                    
                    for (int i = 0; i<3-kdMasuk; i++) {
                        nomor = "0" + nomor;
                    }
                    kdKriteria.setText("Nil-" + nomor);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal " +e.getMessage());
        }
    }
    
    protected void dataTable() {
        DefaultTableModel tabelDataPengeluaran = new DefaultTableModel();
        tabelDataPengeluaran.addColumn("No");
        tabelDataPengeluaran.addColumn("Kode Nilai");
        tabelDataPengeluaran.addColumn("Nama Kandidat");
        tabelDataPengeluaran.addColumn("penampilan");
        tabelDataPengeluaran.addColumn("Attitude");
        tabelDataPengeluaran.addColumn("Komunikasi");
        tabelDataPengeluaran.addColumn("Pengalaman");
        tabelDataPengeluaran.addColumn("Karakter");
        
        try {
            int no = 1;
            String sql = "SELECT nilai.kd_nil, recruitment.nama_kandidat, nilai.penampilan, nilai.attitude, nilai.komunikasi, nilai.pengalaman, nilai.karakter " 
                       + "FROM `nilai` "
                       + "INNER JOIN recruitment ON nilai.kd_kan =  recruitment.kd_kan "
                       + "WHERE recruitment.nama_kandidat LIKE '%"+cariRecruiter.getText()+"%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                tabelDataPengeluaran.addRow(new Object[]{
                   no++,
                   rs.getString(1),
                   rs.getString(2),
                   rs.getString(3),
                   rs.getString(4),
                   rs.getString(5),
                   rs.getString(6),
                   rs.getString(7),
                });
            }
            tabelRecruiter.setModel(tabelDataPengeluaran);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal a "+e.getMessage());
        }
    }
    
    public void bobotTable() {
        DefaultTableModel tabelDataBobot = new DefaultTableModel();
        tabelDataBobot.addColumn("Kode Kriteria");
        tabelDataBobot.addColumn("Penampilan");
        tabelDataBobot.addColumn("Attitude");
        tabelDataBobot.addColumn("Komunikasi");
        tabelDataBobot.addColumn("Pengalaman");
        tabelDataBobot.addColumn("Karakter");
        
        try{
            String sql = "SELECT * FROM kriteria";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                tabelDataBobot.addRow(new Object[]{
                  rs.getString(1),
                  rs.getString(2),
                  rs.getString(3),
                  rs.getString(4),
                  rs.getString(5),
                  rs.getString(6),
                });
            }
            tabelBobot.setModel(tabelDataBobot);
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal " + e.getMessage());
        }
    }
    
    private void tabelRecruiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRecruiterMouseClicked
        // TODO add your handling code here:
       int bar = tabelRecruiter.getSelectedRow();
        TableModel model = tabelRecruiter.getModel();
        kdKriteria.setText(model.getValueAt(bar, 1).toString());
        kdRecruiter.setText(model.getValueAt(bar, 2).toString());
        String pen = model.getValueAt(bar, 3).toString();
        if(pen.equals("1")){
            pen1.setSelected(true);
        } else if (pen.equals("3")){
            pen2.setSelected(true);
        } else {
            pen3.setSelected(true);
        }
        String att = model.getValueAt(bar, 4).toString();
        if(att.equals("1")){
            a1.setSelected(true);
        } else if (att.equals("3")){
            a2.setSelected(true);
        } else {
            a3.setSelected(true);
        }
        String kom = model.getValueAt(bar, 5).toString();
        if(kom.equals("1")){
            k1.setSelected(true);
        } else if (kom.equals("3")){
            k2.setSelected(true);
        } else {
            k3.setSelected(true);
        }
        String peng = model.getValueAt(bar, 6).toString();
        if(peng.equals("1")){
            peng1.setSelected(true);
        } else if (peng.equals("3")){
            peng2.setSelected(true);
        } else {
            peng3.setSelected(true);
        }
        String kar = model.getValueAt(bar, 7).toString();
        if(kar.equals("1")){
            ka1.setSelected(true);
        } else if (kar.equals("3")){
            ka2.setSelected(true);
        } else {
            ka3.setSelected(true);
        }
    }//GEN-LAST:event_tabelRecruiterMouseClicked

    private void cariRecruiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariRecruiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariRecruiterActionPerformed

    private void cariRecruiterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariRecruiterKeyReleased
        // TODO add your handling code here:
        //        dataTable();
    }//GEN-LAST:event_cariRecruiterKeyReleased

    private void hapusPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPenjualan1ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0) {
            String sql = "DELETE FROM nilai WHERE `nilai`.`kd_nil` = '" + kdKriteria.getText()+ "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                kdKriteria.requestFocus();
                dataTable();
                kdBarangKeluar();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }
    }//GEN-LAST:event_hapusPenjualan1ActionPerformed

    private void tambahPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenjualan1ActionPerformed
        // TODO add your handling code here:

        String sql = "INSERT INTO `nilai` (`kd_nil`, `kd_kan`, `penampilan`, `attitude`, `komunikasi`, `pengalaman`, `karakter`) VALUES (?, ?, ?, ?, ?, ?,?);";
        int penampilan = 0;
        int attitude = 0;
        int komunikasi = 0;
        int pengalaman = 0;
        int karakter = 0;
        try {
            if(pen1.isSelected())
                penampilan = 1;
            if(pen2.isSelected())
                penampilan = 3;
            if(pen3.isSelected())
                penampilan = 5;
            if(a1.isSelected())
                attitude = 1;
            if(a2.isSelected())
                attitude = 3;
            if(a3.isSelected())
                attitude = 5;
            if(k1.isSelected())
                komunikasi = 1;
            if(k2.isSelected())
                komunikasi = 3;
            if(k3.isSelected())
                komunikasi = 5;
            if(peng1.isSelected())
                pengalaman = 1;
            if(peng2.isSelected())
                pengalaman = 3;
            if(peng3.isSelected())
                pengalaman = 5;
            if(ka1.isSelected())
                karakter = 1;
            if(ka2.isSelected())
                karakter = 3;
            if(ka3.isSelected())
                karakter = 5;
            
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kdKriteria.getText());
            stat.setString(2, kdRecruiter.getText());
            stat.setInt(3, penampilan);
            stat.setInt(4, attitude);
            stat.setInt(5, komunikasi);
            stat.setInt(6, pengalaman);
            stat.setInt(7, karakter);
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            dataTable();
            kdBarangKeluar();
        }

        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_tambahPenjualan1ActionPerformed

    private void kdRecruiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdRecruiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdRecruiterActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
        kdBarangKeluar();
    }//GEN-LAST:event_resetActionPerformed

    private void kdKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdKriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdKriteriaActionPerformed

    private void pilihBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBarangActionPerformed
        // TODO add your handling code here:
        new Recruiter().setVisible(true);
    }//GEN-LAST:event_pilihBarangActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE `nilai` SET `penampilan` = ?, `attitude` = ?, `komunikasi` = ?, `pengalaman` = ?, `karakter` = ? WHERE `nilai`.`kd_nil` = ?";
        int penampilan = 0;
        int attitude = 0;
        int komunikasi = 0;
        int pengalaman = 0;
        int karakter = 0;
        try {
            if(pen1.isSelected())
                penampilan = 1;
            if(pen2.isSelected())
                penampilan = 3;
            if(pen3.isSelected())
                penampilan = 5;
            if(a1.isSelected())
                attitude = 1;
            if(a2.isSelected())
                attitude = 3;
            if(a3.isSelected())
                attitude = 5;
            if(k1.isSelected())
                komunikasi = 1;
            if(k2.isSelected())
                komunikasi = 3;
            if(k3.isSelected())
                komunikasi = 5;
            if(peng1.isSelected())
                pengalaman = 1;
            if(peng2.isSelected())
                pengalaman = 3;
            if(peng3.isSelected())
                pengalaman = 5;
            if(ka1.isSelected())
                karakter = 1;
            if(ka2.isSelected())
                karakter = 3;
            if(ka3.isSelected())
                karakter = 5;
            
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, penampilan);
            stat.setInt(2, attitude);
            stat.setInt(3, komunikasi);
            stat.setInt(4, pengalaman);
            stat.setInt(5, karakter);
            stat.setString(6, kdKriteria.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            kosong();
            dataTable();
            kdBarangKeluar();
        }

        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Koneksi.getKoneksi();
            String report ="/report/report6.jasper";
            InputStream path = getClass().getResourceAsStream(report);
            HashMap hash = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(path, hash, conn);
            JasperViewer.viewReport(JPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void k1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k1ActionPerformed

    private void k2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k2ActionPerformed

    private void peng2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peng2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peng2ActionPerformed

    private void ka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ka2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ka2ActionPerformed

    private void tabelBobotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBobotMouseClicked
        // TODO add your handling code here:
        int  bar = tabelBobot.getSelectedRow();
        String a = tabelBobot.getValueAt(bar, 0).toString();
        String b = tabelBobot.getValueAt(bar, 1).toString();
        String c = tabelBobot.getValueAt(bar, 2).toString();
        String d = tabelBobot.getValueAt(bar, 3).toString();
        String e = tabelBobot.getValueAt(bar, 4).toString();
        String f = tabelBobot.getValueAt(bar, 5).toString();

        kode.setText(a);
        penampilan.setText(b);
        attitude.setText(c);
        komunikasi.setText(d);
        pengalaman.setText(e);
        karakter.setText(f);
    }//GEN-LAST:event_tabelBobotMouseClicked

    private void penampilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penampilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penampilanActionPerformed

    private void attitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attitudeActionPerformed

    private void komunikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komunikasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komunikasiActionPerformed

    private void pengalamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengalamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengalamanActionPerformed

    private void karakterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karakterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karakterActionPerformed

    private void Update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE `kriteria` SET `penampilan` = ?, `attitude` = ?, `komunikasi` = ?, `pengalaman` = ?, `karakter` = ? WHERE `kriteria`.`kd_kri` = ?";
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, penampilan.getText());
            stat.setString(2, attitude.getText());
            stat.setString(3, komunikasi.getText());
            stat.setString(4, pengalaman.getText());
            stat.setString(5, karakter.getText());
            stat.setString(6, kode.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            bobotTable();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_Update1ActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton Update1;
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    public static final javax.swing.JTextField attitude = new javax.swing.JTextField();
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField cariRecruiter;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapusPenjualan1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JRadioButton k1;
    private javax.swing.JRadioButton k2;
    private javax.swing.JRadioButton k3;
    private javax.swing.JRadioButton ka1;
    private javax.swing.JRadioButton ka2;
    private javax.swing.JRadioButton ka3;
    public static final javax.swing.JTextField karakter = new javax.swing.JTextField();
    public static final javax.swing.JTextField kdKriteria = new javax.swing.JTextField();
    public static final javax.swing.JTextField kdRecruiter = new javax.swing.JTextField();
    public static final javax.swing.JTextField kode = new javax.swing.JTextField();
    public static final javax.swing.JTextField komunikasi = new javax.swing.JTextField();
    private javax.swing.JRadioButton pen1;
    private javax.swing.JRadioButton pen2;
    private javax.swing.JRadioButton pen3;
    public static final javax.swing.JTextField penampilan = new javax.swing.JTextField();
    private javax.swing.JRadioButton peng1;
    private javax.swing.JRadioButton peng2;
    private javax.swing.JRadioButton peng3;
    public static final javax.swing.JTextField pengalaman = new javax.swing.JTextField();
    private javax.swing.JPanel pengeluaranPanel;
    private javax.swing.JButton pilihBarang;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabelBobot;
    private javax.swing.JTable tabelRecruiter;
    private javax.swing.JButton tambahPenjualan1;
    // End of variables declaration//GEN-END:variables
}
