/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import config.Koneksi;

/**
 *
 * @author Rizki Maulana
 */
public class Pelanggan extends javax.swing.JInternalFrame {
    private Connection conn = new Koneksi().getKoneksi();
    private DefaultTableModel tabmode;
    

    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
//        datatable();
        cariData();
        kdPlg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelangganPanel = new javax.swing.JPanel();
        tambahPelanggan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        cariPelanggan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ubahPelanggan = new javax.swing.JButton();
        hapusPelanggan = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        kdPelanggan = new javax.swing.JTextField();
        namaPelanggan = new javax.swing.JTextField();
        alamatPelanggan = new javax.swing.JTextField();
        kontakPelanggan = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        resetPelanggan = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1074, 772));
        getContentPane().setLayout(new java.awt.CardLayout());

        pelangganPanel.setBackground(new java.awt.Color(102, 153, 255));
        pelangganPanel.setPreferredSize(new java.awt.Dimension(1124, 736));
        pelangganPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambahPelanggan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tambahPelanggan.setText("Tambah");
        tambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPelangganActionPerformed(evt);
            }
        });
        pelangganPanel.add(tambahPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 534, -1, -1));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID Pelanggan", "Nama Pelanggan", "Alamat", "Kontak"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablePelanggan);

        pelangganPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 219, 1010, 303));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(232, 238, 204));
        jLabel22.setText("Panel Pelanggan");
        pelangganPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 6, -1, 33));

        cariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganActionPerformed(evt);
            }
        });
        cariPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariPelangganKeyReleased(evt);
            }
        });
        pelangganPanel.add(cariPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 187, 236, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(232, 238, 204));
        jLabel25.setText("Cari");
        pelangganPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 190, -1, -1));

        ubahPelanggan.setText("Ubah");
        ubahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPelangganActionPerformed(evt);
            }
        });
        pelangganPanel.add(ubahPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 534, 70, -1));

        hapusPelanggan.setText("Hapus");
        hapusPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganActionPerformed(evt);
            }
        });
        pelangganPanel.add(hapusPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 534, 70, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(232, 238, 204));
        jLabel23.setText("ID Pelanggan");
        pelangganPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 58, -1, 33));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(232, 238, 204));
        jLabel27.setText("Nama Pelanggan");
        pelangganPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 98, -1, 33));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(232, 238, 204));
        jLabel28.setText("Data Pelanggan");
        pelangganPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 181, -1, 33));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(232, 238, 204));
        jLabel32.setText("Alamat");
        pelangganPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 49, -1, 33));

        kdPelanggan.setEditable(false);
        kdPelanggan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pelangganPanel.add(kdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 61, 224, -1));

        namaPelanggan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pelangganPanel.add(namaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 100, 224, -1));

        alamatPelanggan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pelangganPanel.add(alamatPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 52, 224, -1));

        kontakPelanggan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kontakPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontakPelangganActionPerformed(evt);
            }
        });
        pelangganPanel.add(kontakPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 91, 224, -1));

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(232, 238, 204));
        jLabel33.setText("Kontak");
        pelangganPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 89, -1, 33));

        resetPelanggan.setText("Reset");
        resetPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPelangganActionPerformed(evt);
            }
        });
        pelangganPanel.add(resetPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 534, 70, -1));

        getContentPane().add(pelangganPanel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void aktif() {
        kdPelanggan.setEnabled(true);
        namaPelanggan.setEnabled(true);
        kontakPelanggan.setEnabled(true);
        alamatPelanggan.setEnabled(true);
    }
    
    protected void kosong () {
        kdPelanggan.setText("");
        namaPelanggan.setText("");
        kontakPelanggan.setText("");
        alamatPelanggan.setText("");
    }
    
    public void kdPlg() {
        try {
            String sql = "SELECT MAX(right(kd_pelanggan, 2)) AS kode_pelanggan FROM pelanggan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                if(rs.first()==false) {
                    kdPelanggan.setText("PLG-001");
                } else {
                    rs.last();
                    int id_pelanggan = rs.getInt(1) + 1;
                    String nomor = String.valueOf(id_pelanggan);
                    int idPelanggan = nomor.length();
                    
                    for (int i = 0; i<3-idPelanggan; i++){
                        nomor = "0" + nomor;
                    }
                    kdPelanggan.setText("PLG-" + nomor);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal " + e.getMessage());
        }
    }
    
    public void cariData() {
        DefaultTableModel tabelDataPelanggan = new DefaultTableModel();
        tabelDataPelanggan.addColumn("No");
        tabelDataPelanggan.addColumn("Kode Pelanggan");
        tabelDataPelanggan.addColumn("Nama Pelanggan");
        tabelDataPelanggan.addColumn("Alamat");
        tabelDataPelanggan.addColumn("Kontak");
        
        String cari = cariPelanggan.getText();
        try {
            int no = 1;
            String sql = "SELECT pelanggan.kd_pelanggan AS kode, pelanggan.nama_pelanggan AS nama, pelanggan.alamat AS alamat, pelanggan.kontak AS kontak FROM `pelanggan` WHERE `nama_pelanggan` LIKE '%"+cari+"%' " 
                       + "ORDER BY kd_pelanggan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                tabelDataPelanggan.addRow(new Object[] {
                    no++,
                    rs.getString("kode"),
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("kontak"),
                });
            }
            tablePelanggan.setModel(tabelDataPelanggan);
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal "+ e.getMessage());
        }
    }

    private void tambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPelangganActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO `pelanggan` (`id_pelanggan`, `kd_pelanggan`, `nama_pelanggan`, `alamat`, `kontak`) VALUES (default, ?, ?, ?, ?);";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kdPelanggan.getText());
            stat.setString(2, namaPelanggan.getText());
            stat.setString(3, alamatPelanggan.getText());
            stat.setString(4, kontakPelanggan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            namaPelanggan.requestFocus();
            cariData();
            kdPlg();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_tambahPelangganActionPerformed

    private void cariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariPelangganActionPerformed

    private void ubahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPelangganActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE `pelanggan` SET `nama_pelanggan` = ?, `alamat` = ?, `kontak` = ? WHERE `pelanggan`.`kd_pelanggan` = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, namaPelanggan.getText());
            stat.setString(2, alamatPelanggan.getText());
            stat.setString(3, kontakPelanggan.getText());
            stat.setString(4, kdPelanggan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            namaPelanggan.requestFocus();
            cariData();
            kdPlg();
          
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_ubahPelangganActionPerformed

    private void hapusPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "DELETE FROM pelanggan WHERE kd_pelanggan = '"+kdPelanggan.getText()+"'" ;
            try{
                PreparedStatement stat =conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                namaPelanggan.requestFocus();
                cariData();
                kdPlg();
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e);
            }
        }
    }//GEN-LAST:event_hapusPelangganActionPerformed

    private void kontakPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontakPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kontakPelangganActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void resetPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPelangganActionPerformed
        // TODO add your handling code here:
        kosong();
        cariData();
        
        kdPlg();
    }//GEN-LAST:event_resetPelangganActionPerformed

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
        // TODO add your handling code here:
        int  bar = tablePelanggan.getSelectedRow();
        String a = tablePelanggan.getValueAt(bar, 0).toString();
        String b = tablePelanggan.getValueAt(bar, 1).toString();
        String c = tablePelanggan.getValueAt(bar, 2).toString();
        String d = tablePelanggan.getValueAt(bar, 3).toString();
        String e = tablePelanggan.getValueAt(bar, 4).toString();
        
        kdPelanggan.setText(b);
        namaPelanggan.setText(c);
        alamatPelanggan.setText(d);
        kontakPelanggan.setText(e);
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void cariPelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariPelangganKeyReleased
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_cariPelangganKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPelanggan;
    private javax.swing.JTextField cariPelanggan;
    private javax.swing.JButton hapusPelanggan;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kdPelanggan;
    private javax.swing.JTextField kontakPelanggan;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JPanel pelangganPanel;
    private javax.swing.JButton resetPelanggan;
    private javax.swing.JTable tablePelanggan;
    private javax.swing.JButton tambahPelanggan;
    private javax.swing.JButton ubahPelanggan;
    // End of variables declaration//GEN-END:variables
}
