package views;

import java.sql.*;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalTime;
import java.text.SimpleDateFormat;
import javax.swing.JSpinner;
import config.Koneksi;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rizki Maulana
 */
public class Recruitment extends javax.swing.JInternalFrame {
    private Connection conn = new Koneksi().getKoneksi();
    private DefaultTableModel tabmode;

    /**
     * Creates new form Display
     */
    public Recruitment() {
        initComponents();
        dataTable();
        kdRec();
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penjualanPanel = new javax.swing.JPanel();
        hapusPenjualan = new javax.swing.JButton();
        ubahPenjualan = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kdKan = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cariTransaksi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        cetak = new javax.swing.JButton();

        penjualanPanel.setBackground(new java.awt.Color(102, 153, 255));
        penjualanPanel.setPreferredSize(new java.awt.Dimension(1124, 736));

        hapusPenjualan.setText("Hapus");
        hapusPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPenjualanActionPerformed(evt);
            }
        });

        ubahPenjualan.setText("Update");
        ubahPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPenjualanActionPerformed(evt);
            }
        });

        jScrollPane9.setToolTipText("");
        jScrollPane9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabelTransaksi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Barang Gudang", "Tanggal Masuk Gudang", "Kode Produk", "Stok"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tabelTransaksi);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 238, 204));
        jLabel2.setText("Recruitment");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 238, 204));
        jLabel4.setText("Kode Kandidat");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 238, 204));
        jLabel7.setText("Nama Kandidat");

        kdKan.setEditable(false);
        kdKan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kdKan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdKanActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 238, 204));
        jLabel1.setText("Data Recruitment");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 238, 204));
        jLabel3.setText("Cari");

        cariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTransaksiActionPerformed(evt);
            }
        });
        cariTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTransaksiKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 238, 204));
        jLabel9.setText("Alamat");

        nama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        telp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 238, 204));
        jLabel10.setText("Telepon");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        cetak.setText("Cetak Laporan");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout penjualanPanelLayout = new javax.swing.GroupLayout(penjualanPanel);
        penjualanPanel.setLayout(penjualanPanelLayout);
        penjualanPanelLayout.setHorizontalGroup(
            penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penjualanPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kdKan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(600, 600, 600)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(penjualanPanelLayout.createSequentialGroup()
                            .addComponent(tambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubahPenjualan)
                            .addGap(10, 10, 10)
                            .addComponent(reset)
                            .addGap(10, 10, 10)
                            .addComponent(hapusPenjualan)
                            .addGap(6, 6, 6)
                            .addComponent(cetak))
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        penjualanPanelLayout.setVerticalGroup(
            penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penjualanPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(kdKan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(penjualanPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(penjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambah)
                    .addComponent(ubahPenjualan)
                    .addComponent(reset)
                    .addComponent(hapusPenjualan)
                    .addComponent(cetak))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(penjualanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(penjualanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO `recruitment` (`kd_kan`, `nama_kandidat`, `alamat`, `hp`) VALUES (?, ?, ?, ?)";

        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kdKan.getText());
            stat.setString(2, nama.getText());
            stat.setString(3, alamat.getText());
            stat.setString(4, telp.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            dataTable();
            kdRec();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan " + e);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void cariTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTransaksiKeyReleased
        // TODO add your handling code here:
        dataTable();
    }//GEN-LAST:event_cariTransaksiKeyReleased

    private void cariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTransaksiActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
        kdRec();
    }//GEN-LAST:event_resetActionPerformed

    private void kdKanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdKanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdKanActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
        int bar = tabelTransaksi.getSelectedRow();
        String a = tabelTransaksi.getValueAt(bar, 0).toString();
        String b = tabelTransaksi.getValueAt(bar, 1).toString();
        String c = tabelTransaksi.getValueAt(bar, 2).toString();
        String d = tabelTransaksi.getValueAt(bar, 3).toString();
        String e = tabelTransaksi.getValueAt(bar, 4).toString();

        kdKan.setText(b);
        nama.setText(c);
        alamat.setText(d);
        telp.setText(e);
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void ubahPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPenjualanActionPerformed
        // TODO add your handling code here:
                try {
                        String sql = "UPDATE `recruitment` SET `nama_kandidat` = ?, `alamat` = ?, `hp` = ? WHERE `recruitment`.`kd_kan` = ?";
                        PreparedStatement stat = conn.prepareStatement(sql);
                        stat.setString(1, nama.getText());
                        stat.setString(2, alamat.getText());
                        stat.setString(3, telp.getText());
                        stat.setString(4, kdKan.getText());
            
                        stat.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                        kosong();
                        nama.requestFocus();
                        kdRec();
                        dataTable();
            
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
                    }
    }//GEN-LAST:event_ubahPenjualanActionPerformed

    private void hapusPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPenjualanActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0) {
            String sql = "DELETE FROM recruitment WHERE `recruitment`.`kd_kan` = '" + kdKan.getText()+ "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                kdRec();
                dataTable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }
    }//GEN-LAST:event_hapusPenjualanActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Koneksi.getKoneksi();
            String report ="/report/report5.jasper";
            InputStream path = getClass().getResourceAsStream(report);
            HashMap hash = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(path, hash, conn);
            JasperViewer.viewReport(JPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }//GEN-LAST:event_cetakActionPerformed

    public void kosong() {
        kdKan.setText("");
        nama.setText("");
        telp.setText("");
        alamat.setText("");
    }
    
    // isi otomatis 
    public void kdRec() {
        try{
            String sql = "SELECT MAX(right(kd_kan , 2)) AS kode_kandidat FROM recruitment";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                if(rs.first()==false) {
                    kdKan.setText("Kan-001");
                } else {
                    rs.last();
                    int id_produk = rs.getInt(1) + 1;
                    String nomor = String.valueOf(id_produk);
                    int idProduk = nomor.length();
                    
                    for (int i = 0; i<3-idProduk; i++){
                        nomor = "0" + nomor;
                    }
                    kdKan.setText("Kan-" + nomor);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal "+ e.getMessage());
        }
    }
    
    public void dataTable() {
        DefaultTableModel tabelDataProduk = new DefaultTableModel();
        tabelDataProduk.addColumn("No");
        tabelDataProduk.addColumn("Kode Kandidat");
        tabelDataProduk.addColumn("Nama Kandidat");
        tabelDataProduk.addColumn("Alamat");
        tabelDataProduk.addColumn("Nomor hp");
        
        try {
            int no = 1;
            String sql = "SELECT * FROM `recruitment` WHERE `nama_kandidat` LIKE '%"+cariTransaksi.getText()+"%' ";
                      
                       
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                tabelDataProduk.addRow(new Object[]{
                    no++,
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                });
            }
            tabelTransaksi.setModel(tabelDataProduk);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Konesi gagal "+e.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField cariTransaksi;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapusPenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField kdKan;
    public static final javax.swing.JTextField nama = new javax.swing.JTextField();
    private javax.swing.JPanel penjualanPanel;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tambah;
    public static final javax.swing.JTextField telp = new javax.swing.JTextField();
    private javax.swing.JButton ubahPenjualan;
    // End of variables declaration//GEN-END:variables
}
