/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.sql.*;
import config.Koneksi;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rizki Maulana
 */
public class Stackholders extends javax.swing.JInternalFrame {
    private Connection conn = new Koneksi().getKoneksi();
    private DefaultTableModel tabmode;
    
    
    /**
     * Creates new form BarangMasukDisplay
     */
    public Stackholders() {
        initComponents();
        kdStakeholders();
        dataTable();
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengeluaranPanel = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tabelPengeluaran = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        cariBarangMasuk = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        hapusPenjualan3 = new javax.swing.JButton();
        tambahPenjualan3 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Jabatan = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        reset1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        cetak = new javax.swing.JButton();
        jab = new javax.swing.JComboBox<>();

        pengeluaranPanel.setBackground(new java.awt.Color(102, 153, 255));
        pengeluaranPanel.setPreferredSize(new java.awt.Dimension(1124, 736));
        pengeluaranPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPengeluaran.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabelPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pengeluaran", "Tanggal Pengeluaran", "Kode Produk", "Barang Dibeli", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tabelPengeluaran);

        pengeluaranPanel.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 999, 256));

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(232, 238, 204));
        jLabel42.setText("Cari");
        pengeluaranPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 240, 30, 22));

        cariBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBarangMasukActionPerformed(evt);
            }
        });
        cariBarangMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariBarangMasukKeyReleased(evt);
            }
        });
        pengeluaranPanel.add(cariBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 242, 210, -1));

        jLabel43.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(232, 238, 204));
        jLabel43.setText("Data Stakeholders");
        pengeluaranPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 33));

        hapusPenjualan3.setText("Hapus");
        hapusPenjualan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPenjualan3ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(hapusPenjualan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 549, -1, -1));

        tambahPenjualan3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tambahPenjualan3.setText("Tambah");
        tambahPenjualan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenjualan3ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(tambahPenjualan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 549, -1, -1));

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(232, 238, 204));
        jLabel44.setText("Stakeholders");
        pengeluaranPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, 33));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(232, 238, 204));
        jLabel19.setText("Nama");
        pengeluaranPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 157, 39));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(232, 238, 204));
        jLabel20.setText("Kode Stakeholder");
        pengeluaranPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 39));

        nama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 102, 222, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 549, -1, -1));

        kdStakeholder.setEditable(false);
        kdStakeholder.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kdStakeholder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdStakeholderActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(kdStakeholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 57, 222, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(232, 238, 204));
        jLabel23.setText("Jabatan");
        pengeluaranPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 157, 39));

        Jabatan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Jabatan.setForeground(new java.awt.Color(232, 238, 204));
        Jabatan.setText("Alamat");
        pengeluaranPanel.add(Jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 70, 157, 39));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(232, 238, 204));
        jLabel24.setText("No. Telepon");
        pengeluaranPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 147, -1, 39));

        telp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 154, 222, -1));

        reset1.setText("Update");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 549, -1, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        pengeluaranPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 50, 222, 84));

        cetak.setText("Cetak Laporan");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 549, -1, -1));

        jab.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Investor", "Co-Owner", "Owner" }));
        jab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabActionPerformed(evt);
            }
        });
        pengeluaranPanel.add(jab, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 147, 222, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void kosong() {
        nama.setText("");
        alamat.setText("");
        telp.setText("");
    }
    
    public void kdStakeholders() {
        try{
            String sql = "SELECT MAX(right(kd_sh , 2)) AS kode_stakeholders FROM stakeholders";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                if(rs.first()==false) {
                    kdStakeholder.setText("Sh-001");
                } else {
                    rs.last();
                    int id_produk = rs.getInt(1) + 1;
                    String nomor = String.valueOf(id_produk);
                    int idProduk = nomor.length();
                    
                    for (int i = 0; i<3-idProduk; i++){
                        nomor = "0" + nomor;
                    }
                    kdStakeholder.setText("Sh-" + nomor);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal "+ e.getMessage());
        }
    }
    
    //show table
    protected void dataTable() {
        DefaultTableModel tabelDataProduk = new DefaultTableModel();
        tabelDataProduk.addColumn("No");
        tabelDataProduk.addColumn("Kode Stakeholder");
        tabelDataProduk.addColumn("Nama");
        tabelDataProduk.addColumn("Jabatan");
        tabelDataProduk.addColumn("Alamat");
        tabelDataProduk.addColumn("No. Telepon");
        
        try {
            int no = 1;
            String sql = "SELECT * FROM `stakeholders`"
                       + "WHERE `nama` LIKE '%"+cariBarangMasuk.getText()+"%' ";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                tabelDataProduk.addRow(new Object[]{
                    no++,
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                });
            }
            tabelPengeluaran.setModel(tabelDataProduk);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Konesi gagal "+e.getMessage());
        }
    }
    
    private void tabelPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengeluaranMouseClicked
        // TODO add your handling code here:
        int bar = tabelPengeluaran.getSelectedRow();
        String a = tabelPengeluaran.getValueAt(bar, 0).toString();
        String b = tabelPengeluaran.getValueAt(bar, 1).toString();
        String c = tabelPengeluaran.getValueAt(bar, 2).toString();
        String d = tabelPengeluaran.getValueAt(bar, 3).toString();
        String e = tabelPengeluaran.getValueAt(bar, 4).toString();
        String f = tabelPengeluaran.getValueAt(bar, 5).toString();

        kdStakeholder.setText(b);
        nama.setText(c);
        jab.setSelectedItem(d);
        alamat.setText(e);
        telp.setText(f);
    }//GEN-LAST:event_tabelPengeluaranMouseClicked

    private void cariBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBarangMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariBarangMasukActionPerformed

    private void cariBarangMasukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariBarangMasukKeyReleased
        // TODO add your handling code here:
                dataTable();
    }//GEN-LAST:event_cariBarangMasukKeyReleased

    private void hapusPenjualan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPenjualan3ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0) {
            String sql = "DELETE FROM stakeholders WHERE `stakeholders`.`kd_sh` = '" + kdStakeholder.getText()+ "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                dataTable();
                kdStakeholders();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        }
    }//GEN-LAST:event_hapusPenjualan3ActionPerformed

    private void tambahPenjualan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenjualan3ActionPerformed
        // TODO add your handling code here:
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String sql = "INSERT INTO `stakeholders` (`kd_sh`, `nama`, `jabatan`, `alamat`, `hp`) VALUES (?, ?, ?, ?, ?)";

        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kdStakeholder.getText());
            stat.setString(2, nama.getText());
            stat.setString(3, String.valueOf(jab.getSelectedItem().toString()));
            stat.setString(4, alamat.getText());
            stat.setString(5, telp.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            dataTable();
            kdStakeholders();
        }

        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_tambahPenjualan3ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        dataTable();
        kdStakeholders();
    }//GEN-LAST:event_resetActionPerformed

    private void kdStakeholderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdStakeholderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdStakeholderActionPerformed

    private void telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE `stakeholders` SET `nama` = ?, `jabatan` = ?, `alamat` = ?, `hp` = ? WHERE `stakeholders`.`kd_sh` = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, nama.getText());
            stat.setString(2, String.valueOf(jab.getSelectedItem().toString()));
            stat.setString(3, alamat.getText());
            stat.setString(4, telp.getText());
            stat.setString(5, kdStakeholder.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            nama.requestFocus();
            dataTable();
            kdStakeholders();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_reset1ActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Koneksi.getKoneksi();
            String report ="/report/report1.jasper";
            InputStream path = getClass().getResourceAsStream(report);
            HashMap hash = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(path, hash, conn);
            JasperViewer.viewReport(JPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal " + e);
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void jabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jabatan;
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField cariBarangMasuk;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapusPenjualan3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JComboBox<String> jab;
    public static final javax.swing.JTextField kdStakeholder = new javax.swing.JTextField();
    public static final javax.swing.JTextField nama = new javax.swing.JTextField();
    private javax.swing.JPanel pengeluaranPanel;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JTable tabelPengeluaran;
    private javax.swing.JButton tambahPenjualan3;
    public static final javax.swing.JTextField telp = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
